###############
## 
####


GPU: [0,1]

VERBOSE: True

MODEL:
  MODE: 'Deraining'
  SESSION: 'M3SNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 32
  NUM_EPOCHS: 95000000
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 1e-3
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 100
  RESUME: True
  TRAIN_PS: 256
  VAL_PS: 256
  TRAIN_DIR: './Datasets/GoPr/train' # path to training data
  VAL_DIR: './Datasets/GoPr/test'    # path to validation data
  SAVE_DIR: './checkpoints'     # path to save models and images
  # SAVE_IMAGES: False
